# Generated by Django 4.1.5 on 2023-01-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyectos_wrapper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="pics")),
                ("descripcion", models.CharField(max_length=50)),
            ],
        ),
    ]
