# Generated by Django 4.1.5 on 2023-01-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_post_proyectofoto"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="proyectofoto",),
    ]
