# Generated by Django 4.1.5 on 2023-01-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_post_proyectofoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="proyectofotos",
            field=models.ManyToManyField(to="base.proyectos_foto"),
        ),
    ]
