# Generated by Django 4.1.5 on 2023-01-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_post_proyectofotos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="proyectofotos",
            field=models.ManyToManyField(null=True, to="base.proyectos_foto"),
        ),
    ]
