# Generated by Django 4.1.5 on 2023-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_post_proyectofotos"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
