# Generated by Django 4.1.5 on 2023-01-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_post_body_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="sub_title",
            field=models.TextField(blank=True, null=True),
        ),
    ]
