# Generated by Django 4.1.5 on 2023-01-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_remove_post_sub_title_post_area_post_tiposervicio_and_more"),
    ]

    operations = [
        migrations.RenameField(model_name="post", old_name="body", new_name="body1",),
        migrations.AddField(
            model_name="post",
            name="body2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="body3",
            field=models.TextField(blank=True, null=True),
        ),
    ]
