# Generated by Django 4.1.5 on 2023-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_rename_body_post_body1_post_body2_post_body3"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="moodboard",
            field=models.ImageField(null=True, upload_to="moodboard"),
        ),
    ]
