# Generated by Django 4.1.5 on 2023-01-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_post_moodboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="moodboard",
            field=models.ImageField(blank=True, null=True, upload_to="moodboard"),
        ),
    ]
