# Generated by Django 4.1.5 on 2023-01-21 04:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body1",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
