# Generated by Django 4.1.5 on 2023-01-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_alter_post_body1"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="body2",),
        migrations.RemoveField(model_name="post", name="body3",),
    ]
