# Generated by Django 4.1.5 on 2023-05-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_remove_post_body2_remove_post_body3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="proyectofotos",
            field=models.ManyToManyField(blank=True, to="base.proyectos_foto"),
        ),
    ]
